### PR TITLE
Reset player rotation when colliding with a air launching spring

### PR DESCRIPTION
**Pull request by Renhoex**

### CODE REVIEW

**Comment by NeonSRB2** [comment]
Yay, ren fixed that one spring that i hate

dont mind if i take that right now

**Comment by Renhoex** [comment]
yeah, just waiting for the change to be reviewed before merging it

**Comment by NeonSRB2** [comment]
Just tried porting the changes to cc and... it doesn't work, still does angle shenanigans when sprung.

Can you confirm that the issue is actually fixed here somehow?

**Comment by NeonSRB2** [comment]
Reproducible example: put a diagonal spring on a large, 45 degree slope. The spring should not spring you either directly sideways or upward, but it does anyway.

**Comment by Renhoex** [comment]
should be clear when i said review I meant from someone else on the team, wasn't aware this was an issue with diagonal springs too, it's late here so I'll try to get to this soon

**Comment by Caverns4** [comment]
The issue with the spring seems to be fixed, I see no problems.
Neon, I'll fix the issue you reported momentarily.

**Pull request merged**
